name:  CI/CD ecoomerce

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: docker.io
  FRONT_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/frontend
  BACK_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/backend
  NAMESPACE: app-demo

jobs:
  build-and-deploy:
    name: Build, Push and Deploy to K3s
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push FRONTEND image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.FRONT_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.FRONT_IMAGE }}:latest
          cache-to: type=inline

      - name: Build and push BACKEND image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.BACK_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.BACK_IMAGE }}:latest
          cache-to: type=inline

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Configure kubectl access
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/ -n $NAMESPACE
          kubectl rollout restart deployment backend -n $NAMESPACE
          kubectl rollout restart deployment frontend -n $NAMESPACE
          kubectl get pods -n $NAMESPACE
